"use client";

import { useState } from "react";
import Link from "next/link";
import { 
  ArrowLeft, CheckCircle, AlertTriangle, XCircle, 
  FileText, Shield, User, Scale, Gavel, Printer, Download 
} from "lucide-react";

export default function InvoiceDetailView({ invoice }: { invoice: any }) {
  const [mode, setMode] = useState<"LEGAL" | "OWNER">("LEGAL");

  // Handle Print/Download
  const handleDownload = () => {
    window.print();
  };

  const getRiskBadge = (level: string) => {
    const styles = {
      LOW: "bg-emerald-100 text-emerald-800 border-emerald-200",
      MEDIUM: "bg-amber-100 text-amber-800 border-amber-200",
      HIGH: "bg-red-100 text-red-800 border-red-200",
    };
    return (
      <span className={`px-3 py-1 rounded-full text-sm font-bold border ${styles[level as keyof typeof styles] || "bg-gray-100"}`}>
        {level} RISK
      </span>
    );
  };

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 print:p-0">
      
      {/* --- PRINT ONLY HEADER (Visible only on PDF) --- */}
      <div className="hidden print:block mb-8 border-b-2 border-slate-800 pb-4">
        <h1 className="text-2xl font-bold uppercase tracking-widest">Forensic Audit Report</h1>
        <div className="flex justify-between text-sm mt-2">
          <p>Generated by: MSME Compliance Agent (Gemini AI)</p>
          <p>Date: {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* --- TOP BAR (Hidden on Print) --- */}
      <div className="flex flex-col md:flex-row justify-between items-center mb-8 gap-4 no-print">
        <Link href="/history" className="flex items-center text-slate-500 hover:text-slate-900 transition font-medium">
          <ArrowLeft size={20} className="mr-2" /> Back to History
        </Link>

        <div className="flex items-center gap-3">
           {/* Toggle Switch */}
          <div className="bg-slate-100 p-1 rounded-lg flex items-center shadow-inner">
            <button
              onClick={() => setMode("LEGAL")}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-bold transition-all ${
                mode === "LEGAL" ? "bg-white text-slate-900 shadow-sm" : "text-slate-500"
              }`}
            >
              <Scale size={16} /> Legal
            </button>
            <button
              onClick={() => setMode("OWNER")}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-bold transition-all ${
                mode === "OWNER" ? "bg-amber-500 text-white shadow-sm" : "text-slate-500"
              }`}
            >
              <User size={16} /> Owner
            </button>
          </div>
          
          {/* Download Button */}
          <button 
            onClick={handleDownload}
            className="bg-slate-900 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2 hover:bg-slate-800 transition shadow-lg"
          >
            <Download size={18} /> Export PDF
          </button>
        </div>
      </div>

      {/* --- HEADER CARD --- */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 mb-8 relative overflow-hidden print:shadow-none print:border print:border-slate-900">
        {mode === "OWNER" && (
           <div className="absolute top-0 left-0 w-full h-2 bg-amber-500 no-print" />
        )}
        <div className="flex justify-between items-start relative z-10">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">{invoice.vendorName}</h1>
            <p className="text-slate-500 flex items-center gap-2 font-mono text-sm print:text-slate-900">
              <FileText size={14} /> ID: {invoice.id}
            </p>
          </div>
          <div className="text-right">
            <div className="text-3xl font-bold text-slate-900">
              {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(invoice.amount)}
            </div>
            <div className="mt-2">
              {getRiskBadge(invoice.complianceRiskLevel || "UNKNOWN")}
            </div>
          </div>
        </div>
      </div>

      {/* --- CONTENT GRID --- */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 print:block">
        
        {/* LEFT: ANALYSIS */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 print:shadow-none print:border-none print:p-0 print:mb-6">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <Gavel className="text-blue-600 print:text-black" /> Regulatory Analysis
          </h2>

          <div className={`p-6 rounded-xl border leading-relaxed ${
            mode === "LEGAL" 
              ? "bg-slate-50 border-slate-200 text-slate-700 font-serif" 
              : "bg-amber-50 border-amber-200 text-slate-800 font-sans"
          } print:bg-white print:border-slate-300 print:text-black`}>
            
             <h4 className="font-bold text-sm text-slate-500 uppercase mb-2 print:text-black">
               {mode === "LEGAL" ? "Forensic Observation" : "Action Required"}
             </h4>
             
             {/* Content */}
             {mode === "LEGAL" ? (
               <p>{invoice.legalImpact || invoice.aiSummary}</p>
             ) : (
               <p>
                 {invoice.complianceRiskLevel === "HIGH" 
                   ? "DO NOT PAY. GSTIN Invalid. Credit will be blocked." 
                   : "SAFE TO PAY. Vendor is compliant."}
               </p>
             )}
          </div>
        </div>

        {/* RIGHT: CHECKLIST */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 print:shadow-none print:border-none print:p-0">
          <h2 className="text-xl font-bold mb-6">Compliance Checklist</h2>
          <ul className="space-y-4">
            <li className="flex items-center justify-between p-3 rounded-lg bg-slate-50 print:bg-white print:border-b">
              <span className="text-slate-600 print:text-black">GSTIN Validation</span>
              {invoice.isGstMissing ? (
                <span className="text-red-600 font-bold">FAILED</span>
              ) : (
                <span className="text-emerald-600 font-bold">PASSED</span>
              )}
            </li>
            <li className="flex items-center justify-between p-3 rounded-lg bg-slate-50 print:bg-white print:border-b">
              <span className="text-slate-600 print:text-black">Restricted Goods</span>
              {invoice.isRegulatoryItem ? (
                 <span className="text-amber-600 font-bold">YES</span>
              ) : (
                 <span className="text-slate-500 font-bold">NO</span>
              )}
            </li>
            <li className="flex items-center justify-between p-3 rounded-lg bg-slate-50 print:bg-white print:border-b">
              <span className="text-slate-600 print:text-black">Tax Calculation</span>
               <span className="text-emerald-600 font-bold">ACCURATE</span>
            </li>
          </ul>
        </div>
      </div>

      {/* --- PRINT FOOTER --- */}
      <div className="print-footer text-slate-500">
        <p>Digitally Audited by MSME Compliance Agent • Immutable Log ID: {invoice.id}</p>
      </div>

    </div>
  );
}