import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generatePDF(data: any) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(41, 128, 185);
  doc.text("Forensic Compliance Audit", 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Vendor: ${data.vendorName}`, 14, 28);

  // Compliance Risk Badge
  doc.setFillColor(data.complianceRiskLevel === 'HIGH' ? 231 : 235, data.complianceRiskLevel === 'HIGH' ? 76 : 245, data.complianceRiskLevel === 'HIGH' ? 60 : 245);
  doc.rect(14, 35, 180, 12, 'F');
  doc.setTextColor(data.complianceRiskLevel === 'HIGH' ? 255 : 0);
  doc.setFontSize(12);
  doc.text(`COMPLIANCE RISK LEVEL: ${data.complianceRiskLevel}`, 20, 42);

  // Legal Impact
  doc.setTextColor(0);
  doc.setFontSize(11);
  doc.text("Legal Impact Analysis:", 14, 55);
  doc.setFont("helvetica", "italic");
  const impactLines = doc.splitTextToSize(data.legalImpact, 180);
  doc.text(impactLines, 14, 62);

  // The Big Data Table
  const tableData = [
    ["Vendor", data.vendorName],
    ["GSTIN Status", data.isGstMissing ? "MISSING (Critical)" : data.gstNumber],
    ["Regulatory Goods", data.isRegulatoryItem ? "YES (Pharma/Controlled)" : "No"],
    ["License Required", data.requiresLicense ? "YES (Verify FSSAI/Drug)" : "No"],
    ["Currency Check", data.currencyMismatch ? "MISMATCH Detected" : "Matched"],
    ["Total Amount", `${data.currency} ${data.totalAmount}`],
  ];

  autoTable(doc, {
    startY: 80,
    head: [['Audit Parameter', 'Finding']],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: data.complianceRiskLevel === 'HIGH' ? [192, 57, 43] : [41, 128, 185] 
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 60 },
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by AI MSME Compliance Agent. Not a substitute for legal advice.", 14, 280);

  doc.save(`Forensic_Report_${data.vendorName}.pdf`);
}